title: "Red Green Blue: Test Driven Development"   # Optional: Your site name
description: "Here you'll find the About, Writing Logs, Timeline." # Optional: A short description
theme: jekyll-theme-midnight
